version: '2'

networks:
  mymarket:
    external:
      name: my-net

services:
  eventsclient:
    container_name: eventsclient
    image: mjkong/eventsclient
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
      - CORE_PEER_LOCALMSPID=Store1MSP
      - CORE_PEER_MSPCONFIGPATH=/root/crypto/msp
      - SERVER=peer0.store1.mymarket.com:7051
      - CHANNELID=mymarketcc
      - FILTERED=false
      - TLS=true
      - CLIENTKEY=/root/crypto/tls/client.key
      - CLIENTCERT=/root/crypto/tls/client.crt
      - ROOTCERT=/root/crypto/tls/ca.crt
    volumes:
      - /home/badm/mymarket/crypto-config/peerOrganizations/store1.mymarket.com/peers/peer0.store1.mymarket.com/msp:/root/crypto/msp
      - /home/badm/mymarket/crypto-config/peerOrganizations/store1.mymarket.com/users/Admin@store1.mymarket.com/tls:/root/crypto/tls
    networks:
      - mymarket
